[Program: GCI] (Comment task - Part 2/2) Prepare comment task endpoints [Mentorship - Backend]
asawesome07/mentorship-backend pull request #1
Opened 2020-01-02 11:38 UTC by asawesome07

### Description
Added Task comment model and modified task_dao for task_comment

### Type of Change:
- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
I tested this using `python -m unittest discover tests`

Here's a screenshot
![Capture](https://user-images.githubusercontent.com/29257061/71663314-ba1dda00-2d7a-11ea-8dc2-4a04ba56277e.PNG)

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [x] Update Postman API at /docs folder
- [x] Update Swagger documentation and the exported file at /docs folder

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

2020-01-02 21:37 UTC, annabauza requested changes
hey left you some comments, mostly minor comments and docs :)

2020-01-02 21:37 UTC, annabauza commented on app/database/models/task_comment.py
> +        """Returns a list containing a task."""
List of what?

2020-01-02 21:37 UTC, annabauza commented on app/database/models/task_comment.py
> +    Attributes:
Not sure if those are attributes. Do we use this convention in other enums?

2020-01-02 21:37 UTC, annabauza commented on app/database/models/task_comment.py
> +    def find_by_id(cls, _id):
shell we add mentorship_relation_id here or this is unique?

2020-01-02 21:37 UTC, annabauza commented on app/api/dao/task_comment.py
>              response code.
can we add error response to docs?

2020-01-02 21:37 UTC, annabauza commented on app/api/dao/task_comment.py
>              data: A list containing the comment of the task comment.
This sentence is unclear.

2020-01-02 21:37 UTC, annabauza commented on app/api/dao/task_comment.py
> +        comment = data['comment']
is it single comment or multiple comments? I think name is confusing

2020-01-02 21:37 UTC, annabauza commented on app/api/dao/task_comment.py
> +            return messages.UNACCEPTED_STATE_RELATION, 400
this return is not documented

2020-01-02 21:37 UTC, annabauza commented on app/api/dao/task_comment.py
> +            return messages.TASK_DOES_NOT_EXIST, 404
this return is not documented

2020-01-02 21:37 UTC, annabauza commented on app/api/dao/task_comment.py
> +            return messages.USER_NOT_INVOLVED_IN_THIS_MENTOR_RELATION, 401
this return is not documented

2020-01-02 21:37 UTC, annabauza commented on app/api/dao/task_comment.py
> +            return messages.MENTORSHIP_RELATION_DOES_NOT_EXIST, 404
this return is not documented

2020-01-02 21:37 UTC, annabauza commented on app/api/dao/task_comment.py
> +            return messages.UNACCEPTED_STATE_RELATION, 400
this return is not documented

2020-01-02 21:37 UTC, annabauza commented on app/api/dao/task_comment.py
> +            return messages.TASK_DOES_NOT_EXIST, 404
this return is not documented

2020-01-02 21:37 UTC, annabauza commented on app/api/dao/task_comment.py
> +            return messages.USER_NOT_INVOLVED_IN_THIS_MENTOR_RELATION, 401
this return is not documented

2020-01-02 21:37 UTC, annabauza commented on app/api/dao/task_comment.py
> +            return messages.MENTORSHIP_RELATION_DOES_NOT_EXIST, 404
this return is not documented

2020-01-02 21:37 UTC, annabauza commented on app/api/dao/task_comment.py
> +            return messages.UNACCEPTED_STATE_RELATION, 400
this return is not documented

2020-01-02 21:37 UTC, annabauza commented on app/api/dao/task_comment.py
> +            return messages.TASK_DOES_NOT_EXIST, 404
this return is not documented

2020-01-02 21:37 UTC, annabauza commented on app/api/dao/task_comment.py
> +            return messages.USER_NOT_INVOLVED_IN_THIS_MENTOR_RELATION, 401
this return is not documented

2020-01-02 21:37 UTC, annabauza commented on app/api/resources/mentorship_relation.py
> +        # TODO check if user id is well parsed, if it is an integer
you intended to add something here?

2020-01-02 21:37 UTC, annabauza commented on app/api/resources/mentorship_relation.py
> +        List all task comment from a task from a mentorship relation.
comments not comment

2020-01-02 21:37 UTC, annabauza commented on app/api/resources/mentorship_relation.py
> +        # TODO check if user id is well parsed, if it is an integer
again is something missing here?

2020-01-02 21:37 UTC, annabauza commented on app/api/resources/mentorship_relation.py
> +    @mentorship_relation_ns.response(200, 'Task comment was deleted successfully')
delete_comment returns some new codes, should be documented

2020-01-02 21:37 UTC, annabauza commented on app/api/resources/mentorship_relation.py
> +    @mentorship_relation_ns.expect(auth_header_parser)
Shouldn't we add some arguments to documentation?

2020-01-02 21:37 UTC, annabauza commented on app/api/resources/mentorship_relation.py
> +    @mentorship_relation_ns.expect(auth_header_parser)
Shouldn't we add some arguments to documentation?

2020-01-02 21:37 UTC, annabauza commented on app/api/resources/mentorship_relation.py
> +                                     model=list_task_comment_response_body)
it returns some more codes, please fill up.

2020-01-02 21:37 UTC, annabauza commented on app/api/resources/mentorship_relation.py
> +    @mentorship_relation_ns.expect(auth_header_parser, create_task_comment_body)
Shouldn't we add some arguments to documentation?

2020-01-02 21:37 UTC, annabauza commented on app/api/resources/mentorship_relation.py
> +    @mentorship_relation_ns.expect(auth_header_parser, create_task_comment_body)
Shouldn't we add some arguments to documentation?

2020-01-02 21:37 UTC, annabauza commented on app/api/resources/mentorship_relation.py
> +        # TODO check if user id is well parsed, if it is an integer
is something missing here?

2020-01-02 21:37 UTC, annabauza commented on app/api/resources/mentorship_relation.py
> +    @mentorship_relation_ns.response(200, 'Task comment was modified successfully')
this returns some more codes, not only 200.

2020-01-02 21:49 UTC, asawesome07 commented on app/database/models/task_comment.py
> +        """Returns a list containing a task."""
fixed

2020-01-02 21:50 UTC, asawesome07 commented on app/database/models/task_comment.py
> +    Attributes:
yes, this convention is also used to describe a task in tasks_list model.
app/database/models/tasks_list.py

2020-01-02 21:59 UTC, asawesome07 commented on app/database/models/task_comment.py
> +    def find_by_id(cls, _id):
removed the function as it wasn't used

2020-01-02 22:06 UTC, asawesome07 commented on app/api/resources/mentorship_relation.py
> +        List all task comment from a task from a mentorship relation.
fixed

2020-01-02 22:09 UTC, asawesome07 commented on app/api/dao/task_comment.py
>              data: A list containing the comment of the task comment.
fixed

2020-01-02 22:11 UTC, asawesome07 commented on app/api/dao/task_comment.py
> +        comment = data['comment']
fixed

2020-01-02 22:26 UTC, annabauza commented on app/api/dao/task_comment.py
>              data: A list containing the comment of the task comment.
comment of the task comment?

2020-01-02 22:27 UTC, annabauza commented on app/api/dao/task_comment.py
> +        comment = data['comment']
have you pushed changes?

2020-01-02 22:36 UTC, annabauza approved these changes
well done :)

2020-02-09 18:30 UTC, annabauza commented
Can you please merge this PR, so we have everything in one PR? I don't have rights to this repo. Thank you in advance.

2020-02-09 18:43 UTC, merged

2020-02-09 18:44 UTC, asawesome07 commented
> Can you please merge this PR, so we have everything in one PR? I don't have rights to this repo. Thank you in advance.

done